In [9]:
import pandas as pd
import spacy
nlp=spacy.load('en_core_web_sm')
import re

In [2]:
raw_text_data=pd.read_csv('financial_news_events.csv')

In [3]:
raw_text_data

,Date,Headline,Source,Market_Event,Market_Index,Index_Change_Percent,Trading_Volume,Sentiment,Sector,Impact_Level,Related_Company,News_Url
0,2025-05-21,Nikkei 225 index benefits from a weaker yen,Times of India,Commodity Price Shock,DAX,3.52,166.45,NaN,Technology,High,Goldman Sachs,https://timesofindia.indiatimes.com/business/m...
1,2025-05-18,Government subsidy program gives a lift to the...,Financial Times,Central Bank Meeting,Shanghai Composite,-3.39,57.61,NaN,Retail,Low,ExxonMobil,https://timesofindia.indiatimes.com/business/m...
2,2025-06-25,New housing data release shows a slowdown in m...,The Hindu Business Line,Consumer Confidence Report,Shanghai Composite,-0.05,403.22,Neutral,Retail,Medium,Boeing,https://www.moneycontrol.com/us-markets/sp-500
3,2025-07-21,Massive stock buyback program announced by a c...,The Economist,Commodity Price Shock,NSE Nifty,-2.29,100.11,Positive,Consumer Goods,Low,Samsung Electronics,https://www.cnbc.com/2025/09/automotive-indust...
4,2025-07-23,Government spending bill is expected to stimul...,The Motley Fool,Inflation Data Release,Nasdaq Composite,-3.97,438.22,Negative,Consumer Goods,Low,JP Morgan Chase,https://www.bloomberg.com/australia/asx-200-pe...
...,...,...,...,...,...,...,...,...,...,...,...,...
3019,2025-02-11,Tech Giant's New Product Launch Sparks Sector-...,The Motley Fool,Economic Data Release,DAX,-2.22,212.90,Neutral,Industrials,Low,Samsung Electronics,https://www.marketwatch.com/story/consumer-goo...
3020,2025-08-07,Government spending bill is expected to stimul...,Bloomberg,Geopolitical Event,Euro Stoxx 50,-0.17,105.88,Neutral,Aerospace & Defense,Low,Microsoft,https://www.ft.com/content/consumer-confidence...
3021,2025-05-22,Government spending bill is expected to stimul...,The Economist,Market Rally,Shanghai Composite,4.02,152.28,Negative,Telecommunications,Low,Samsung Electronics,https://www.reuters.com/markets/indices/ftse-100
3022,2025-07-17,Pharmaceutical company's drug approval drives ...,Forbes,Economic Data Release,CAC 40,0.12,53.49,Neutral,Healthcare,Medium,Goldman Sachs,https://www.business-standard.com/internationa...
3023,2025-03-07,Real Estate sector shows signs of overheating ...,Times of India,Interest Rate Change,Nasdaq Composite,-1.76,469.95,Negative,Automotive,Medium,Samsung Electronics,https://www.reuters.com/business/retail-sector...

In [7]:
raw_text_data.drop(columns=['Date'	,'Source'	,'Market_Event'	,'Market_Index'	,'Index_Change_Percent'	,'Trading_Volume',	'Sentiment'	,'Sector','Impact_Level','Related_Company','News_Url'],inplace=True)

In [8]:
raw_text_data

                                               Headline
0           Nikkei 225 index benefits from a weaker yen
1     Government subsidy program gives a lift to the...
2     New housing data release shows a slowdown in m...
3     Massive stock buyback program announced by a c...
4     Government spending bill is expected to stimul...
...                                                 ...
3019  Tech Giant's New Product Launch Sparks Sector-...
3020  Government spending bill is expected to stimul...
3021  Government spending bill is expected to stimul...
3022  Pharmaceutical company's drug approval drives ...
3023  Real Estate sector shows signs of overheating ...

[3024 rows x 1 columns]

In [ ]:
def remove_pun_lower(sentence):
    output=sentence.lower()
    output=re.sub(r'[^\w\s]', '', sentence)
    return output
def token_lemma_stop_word(sentence):
    doc=nlp(sentence)
    output=[token.lemma_ for token in doc if not token.is_stop]
    return ' '.join(output)

In [ ]:
def nlp_pipeline(sentence):
    output=sentence.apply(remove_pun_lower)
    output=