In [1]:
import pandas as pd
import re 
import spacy
nlp=spacy.load('en_core_web_sm')

In [2]:
def remove_lower_pun(sentence):
    sentence=sentence.lower()
    sentence=re.sub(r'[^\w\s]', '', sentence)
    return sentence
def token_lemma_stop(sentence):
    doc=nlp(sentence)
    output=[token.lemma_ for token in doc if not token.is_stop]
    return ' '.join(output)

In [3]:
df=pd.read_excel('../../../Popchip_Reviews.xlsx')

In [4]:
df

,Id,UserId,Rating,Priority,Title,Text
0,23689,A21SYVGVNG8RAS,5,Low,Yummy snacks!,Popchips are the bomb!! I use the parmesan ga...
1,23690,AQJYXC0MPRQJL,5,Low,Great chip that is different from the rest,I like the puffed nature of this chip that mak...
2,23691,A30NYUHEDLWI0Y,5,Low,Great Alternative to Potato Chips,I just love these chips! I was always a big f...
3,23692,A2NU55U9LKTB5J,3,High,Not somthing I would crave,"These tasted like potatoe stix, that we got in..."
4,23693,A225F7QFP5LIW2,5,Low,healthy and delicious,These chips are great! They look almost like ...
...,...,...,...,...,...,...
559,24248,A2TX79GR278JMA,5,Low,Life-saver for chip lovers trying to eat healt...,I love potato chips. I could eat them by the ...
560,24249,A3L61VG7RK40TW,5,Low,My Favorite Go-To Snack,"When PopChips were really hard to find, I was ..."
561,24250,A2X9PNKZRBD1UC,5,Low,A healthy alternative,These are a much healthy alternative to most c...
562,24251,A2LPC9SGRB3G4G,5,Low,Luv'em,"These are so good, I've started getting them a..."
563,24252,A1JTN0IZGH3948,4,Low,Good chips!,These are good chips! Maybe not as tasty as so...

In [5]:
df['Text']=df['Text'].apply(remove_lower_pun)
df['Text']=df['Text'].apply(token_lemma_stop)

In [6]:
df

,Id,UserId,Rating,Priority,Title,Text
0,23689,A21SYVGVNG8RAS,5,Low,Yummy snacks!,popchip bomb use parmesan garlic scoop cotta...
1,23690,AQJYXC0MPRQJL,5,Low,Great chip that is different from the rest,like puff nature chip make unique chip market ...
2,23691,A30NYUHEDLWI0Y,5,Low,Great Alternative to Potato Chips,love chip big fan potato chip not discover p...
3,23692,A2NU55U9LKTB5J,3,High,Not somthing I would crave,taste like potatoe stix get grade school lunch...
4,23693,A225F7QFP5LIW2,5,Low,healthy and delicious,chip great look like flattened rice cake tas...
...,...,...,...,...,...,...
559,24248,A2TX79GR278JMA,5,Low,Life-saver for chip lovers trying to eat healt...,love potato chip eat bagful thank power prov...
560,24249,A3L61VG7RK40TW,5,Low,My Favorite Go-To Snack,popchip hard find order case amazon regular ba...
561,24250,A2X9PNKZRBD1UC,5,Low,A healthy alternative,healthy alternative chip taste great great c...
562,24251,A2LPC9SGRB3G4G,5,Low,Luv'em,good ve start get automatically like origina...
563,24252,A1JTN0IZGH3948,4,Low,Good chips!,good chip maybe tasty unhealthy chip definitel...

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english',min_df=0.2)
cv_mat=cv.fit_transform(df['Text'])
cv_mat_df=pd.DataFrame(cv_mat.toarray(),columns=cv.get_feature_names_out())

In [8]:
cv_mat_df

,bag,buy,calorie,chip,eat,flavor,good,great,like,love,popchip,potato,salt,snack,taste,try
0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0
1,0,0,0,4,0,3,0,0,1,1,0,0,2,0,0,1
2,0,0,0,3,0,0,0,1,0,2,1,1,1,0,0,0
3,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0
4,1,0,0,2,1,2,0,1,2,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,0,0,0,3,3,1,1,5,0,1,1,4,0,0,1,0
560,1,0,0,0,0,1,0,1,0,0,1,0,0,1,0,1
561,0,0,0,2,0,1,0,2,0,0,0,0,0,0,2,0
562,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0
563,0,1,0,2,0,0,1,0,0,0,0,0,0,0,0,0

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(stop_words='english',min_df=0.2)
tfidf_mat=tfidf.fit_transform(df['Text'])
tfidf_mat_df=pd.DataFrame(tfidf_mat.toarray(),columns=tfidf.get_feature_names_out())

In [10]:
tfidf_mat_df

,bag,buy,calorie,chip,eat,flavor,good,great,like,love,popchip,potato,salt,snack,taste,try
0,0.000000,0.000000,0.0,0.392603,0.656435,0.000000,0.000000,0.000000,0.000000,0.000000,0.644170,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.0,0.561185,0.000000,0.537701,0.000000,0.000000,0.195524,0.213766,0.000000,0.000000,0.513094,0.000000,0.000000,0.220814
2,0.000000,0.000000,0.0,0.549323,0.000000,0.000000,0.000000,0.313002,0.000000,0.557994,0.300437,0.294179,0.334833,0.000000,0.000000,0.000000
3,0.000000,0.690063,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.512918,0.000000,0.000000,0.000000,0.000000,0.000000,0.510616,0.000000
4,0.267674,0.000000,0.0,0.360830,0.301655,0.460974,0.000000,0.308399,0.502872,0.000000,0.000000,0.289853,0.000000,0.000000,0.250308,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,0.000000,0.000000,0.0,0.237796,0.397597,0.101265,0.114325,0.677476,0.000000,0.120775,0.130056,0.509388,0.000000,0.000000,0.109973,0.000000
560,0.381673,0.000000,0.0,0.000000,0.000000,0.328649,0.000000,0.439742,0.000000,0.000000,0.422089,0.000000,0.000000,0.459181,0.000000,0.404891
561,0.000000,0.000000,0.0,0.399843,0.000000,0.255407,0.000000,0.683486,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.554742,0.000000
562,0.000000,0.000000,0.0,0.000000,0.000000,0.537244,0.606536,0.000000,0.586074,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
563,0.000000,0.605279,0.0,0.645638,0.000000,0.000000,0.465606,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [11]:
y=df['Priority']

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(cv_mat_df,y,test_size=0.2,random_state=0)

In [13]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,classification_report
model=MultinomialNB()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7876106194690266
              precision    recall  f1-score   support

        High       0.33      0.14      0.20        21
         Low       0.83      0.93      0.88        92

    accuracy                           0.79       113
   macro avg       0.58      0.54      0.54       113
weighted avg       0.74      0.79      0.75       113

In [15]:
from sklearn.linear_model import LogisticRegression

model1=LogisticRegression()

X1_train,X1_test,y1_train,y1_test=train_test_split(tfidf_mat_df,y,test_size=0.2)

model1.fit(X1_train,y1_train)

y1_pred=model1.predict(X1_test)

print(accuracy_score(y1_test,y1_pred))

print(classification_report(y1_test,y1_pred))

0.8141592920353983
              precision    recall  f1-score   support

        High       0.75      0.13      0.22        23
         Low       0.82      0.99      0.89        90

    accuracy                           0.81       113
   macro avg       0.78      0.56      0.56       113
weighted avg       0.80      0.81      0.76       113